language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
 - npm install -g @angular/cli

script: 
  - npm run build
  - npm run test-prod
  - cd docs_app && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master